const mcColors = [
    { code: '§0', rgb: [0, 0, 0] }, { code: '§1', rgb: [0, 0, 170] },
    { code: '§2', rgb: [0, 170, 0] }, { code: '§3', rgb: [0, 170, 170] },
    { code: '§4', rgb: [170, 0, 0] }, { code: '§5', rgb: [170, 0, 170] },
    { code: '§6', rgb: [255, 170, 0] }, { code: '§7', rgb: [170, 170, 170] },
    { code: '§8', rgb: [85, 85, 85] }, { code: '§9', rgb: [85, 85, 255] },
    { code: '§a', rgb: [85, 255, 85] }, { code: '§b', rgb: [85, 255, 255] },
    { code: '§c', rgb: [255, 85, 85] }, { code: '§d', rgb: [255, 85, 255] },
    { code: '§e', rgb: [255, 255, 85] }, { code: '§f', rgb: [255, 255, 255] }
];

function findClosestMinecraftColor(r, g, b) {
    let closest = mcColors[0];
    let minDistance = Infinity;
    for (const color of mcColors) {
        const distance = Math.sqrt(Math.pow(r - color.rgb[0], 2) + Math.pow(g - color.rgb[1], 2) + Math.pow(b - color.rgb[2], 2));
        if (distance < minDistance) {
            minDistance = distance;
            closest = color;
        }
    }
    return closest.code;
}

const commandAliases = {
    "/play solobw": "/play bedwars_eight_one",
    "/play doublesbw": "/play bedwars_eight_two",
    "/play 3sbw": "/play bedwars_four_three",
    "/play 4sbw": "/play bedwars_four_four",
    "/play 4v4bw": "/play bedwars_two_four",
    "/play castlebw": "/play bedwars_castle",
    "/play solosw": "/play skywars_solo_normal",
    "/play doublesinsanesw": "/play skywars_teams_insane",
    "/play doublesnormalsw": "/play skywars_teams_normal",
    "/play classicduels": "/play duels_classic_duel",
    "/play bridgeduels": "/play duels_bridge_duel",
    "/play uhcduels": "/play duels_uhc_duel",
    "/play skywarsduels": "/play duels_sw_duel",
    "/play sumoduels": "/play duels_sumo_duel",
    "/play bowduels": "/play duels_bow_duel",
    "/play comboduels": "/play duels_combo_duel",
    "/play opduels": "/play duels_op_duel",
};

const duelsModes = {
    general: { apiName: "Duels", displayName: "Duels", prefix: "" },
    classic: { apiName: "Duels", displayName: "Classic Duels", prefix: "classic_duel" },
    bridge: { apiName: "Duels", displayName: "Bridge Duels", prefix: "bridge_duel" },
    uhc: { apiName: "Duels", displayName: "UHC Duels", prefix: "uhc_duel" },
    skywars: { apiName: "Duels", displayName: "SkyWars Duels", prefix: "sw_duel" },
    sumo: { apiName: "Duels", displayName: "Sumo Duels", prefix: "sumo_duel" },
    bow: { apiName: "Duels", displayName: "Bow Duels", prefix: "bow_duel" },
    combo: { apiName: "Duels", displayName: "Combo Duels", prefix: "combo_duel" },
    op: { apiName: "Duels", displayName: "OP Duels", prefix: "op_duel" }
};

const gameModeMap = {
    "arcade": { apiName: "Arcade", displayName: "Arcade" },
    "arena": { apiName: "Arena", displayName: "Arena Brawl" },
    "bedwars": { apiName: "Bedwars", displayName: "Bed Wars" },
    "bw": { apiName: "Bedwars", displayName: "Bed Wars" },
    "blitz": { apiName: "HungerGames", displayName: "Blitz SG" },
    "sg": { apiName: "HungerGames", displayName: "Blitz SG" },
    "buildbattle": { apiName: "BuildBattle", displayName: "Build Battle" },
    "bb": { apiName: "BuildBattle", displayName: "Build Battle" },
    "cvc": { apiName: "MCGO", displayName: "Cops and Crims" },
    "crazywalls": { apiName: "TrueCombat", displayName: "Crazy Walls" },
    "cw": { apiName: "TrueCombat", displayName: "Crazy Walls" },
    "duels": duelsModes.general,
    "classic": duelsModes.classic, "classicduels": duelsModes.classic,
    "bridge": duelsModes.bridge, "bridgeduels": duelsModes.bridge,
    "uhc": duelsModes.uhc, "uhcduels": duelsModes.uhc,
    "skywarsduels": duelsModes.skywars,
    "sumo": duelsModes.sumo, "sumoduels": duelsModes.sumo,
    "bow": duelsModes.bow, "bowduels": duelsModes.bow,
    "combo": duelsModes.combo, "comboduels": duelsModes.combo,
    "op": duelsModes.op, "opduels": duelsModes.op,
    "megawalls": { apiName: "Walls3", displayName: "Mega Walls" },
    "mw": { apiName: "Walls3", displayName: "Mega Walls" },
    "murder": { apiName: "MurderMystery", displayName: "Murder Mystery" },
    "mm": { apiName: "MurderMystery", displayName: "Murder Mystery" },
    "paintball": { apiName: "Paintball", displayName: "Paintball" },
    "pit": { apiName: "Pit", displayName: "The Pit" },
    "quake": { apiName: "Quake", displayName: "Quake" },
    "quakecraft": { apiName: "Quake", displayName: "Quake" },
    "skyclash": { apiName: "SkyClash", displayName: "SkyClash" },
    "skywars": { apiName: "SkyWars", displayName: "SkyWars" },
    "sw": { apiName: "SkyWars", displayName: "SkyWars" },
    "smash": { apiName: "SuperSmash", displayName: "Smash Heroes" },
    "speeduhc": { apiName: "SpeedUHC", displayName: "Speed UHC" },
    "tnt": { apiName: "TNTGames", displayName: "TNT Games" },
    "tkr": { apiName: "GingerBread", displayName: "Turbo Kart Racers" },
    "turbokartracers": { apiName: "GingerBread", displayName: "Turbo Kart Racers" },
    "uhcchampions": { apiName: "UHC", displayName: "UHC Champions" },
    "vampirez": { apiName: "VampireZ", displayName: "VampireZ" },
    "walls": { apiName: "Walls", displayName: "Walls" },
    "warlords": { apiName: "Battleground", displayName: "Warlords" },
    "wool": { apiName: "WoolGames", displayName: "Wool Wars" },
    "woolwars": { apiName: "WoolGames", displayName: "Wool Wars" },
};

const quickQueueMap = {
  'bedwars2': { name: 'Voidless Doubles', command: '/play bedwars_eight_two_voidless' },
  'bedwars4': { name: 'Voidless 4v4v4v4', command: '/play bedwars_four_four_voidless' },
  'blitzsolo': { name: 'Blitz Solo', command: '/play blitz_solo_normal' },
  'blitzteams': { name: 'Blitz Teams', command: '/play blitz_teams_normal' },
  'buildbattlepro': { name: 'Build Battle Pro', command: '/play build_battle_solo_pro' },
  'buildbattlesolo': { name: 'Build Battle Solo', command: '/play build_battle_solo_normal' },
  'buildbattlesolo114': { name: 'Build Battle Solo (1.14+)', command: '/play build_battle_solo_normal_latest' },
  'buildbattleteams': { name: 'Build Battle Teams', command: '/play build_battle_teams_normal' },
  'cvc': { name: 'Cops and Crims', command: '/play mcgo' },
  'doubles': { name: 'OP Duels (2v2)', command: '/play duels_op_doubles' },
  'infection': { name: 'Murder Mystery Infection', command: '/play murder_infection' },
  'hole': { name: 'Hole in the Wall', command: '/play arcade_hole_in_the_wall' },
  'hypixelsays': { name: 'Hypixel Says', command: '/play arcade_simon_says' },
  'labblizzard': { name: 'SkyWars Laboratory (Blizzard)', command: '/play solo_insane_blizzard' },
  'labhunters': { name: 'SkyWars Laboratory (Hunters vs. Beasts)', command: '/play solo_insane_hunters_vs_beasts' },
  'labkill': { name: 'SkyWars Laboratory (Kill by Color)', command: '/play solo_insane_kill_by_color' },
  'lablava': { name: 'SkyWars Laboratory (Floor is Lava)', command: '/play solo_insane_floor_is_lava' },
  'lucky2': { name: 'Lucky Blocks Doubles', command: '/play bedwars_eight_two_lucky' },
  'lucky4': { name: 'Lucky Blocks 4v4v4v4', command: '/play bedwars_four_four_lucky' },
  'megadoubles': { name: 'Mega SkyWars Doubles', command: '/play mega_doubles' },
  'megawars': { name: 'Mega Walls', command: '/play mw_standard' },
  'megasolo': { name: 'Mega SkyWars Normal', command: '/play mega_normal' },
  'miniwalls': { name: 'Mini Walls', command: '/play arcade_mini_walls' },
  'parkour': { name: 'Hypixel Parkour', command: '/play duels_parkour_eight' },
  'pit': { name: 'The Pit', command: '/play pit' },
  'pixelparty': { name: 'Pixel Party', command: '/play arcade_pixel_party' },
  'pixelpainters': { name: 'Pixel Painters', command: '/play arcade_pixel_painters' },
  'protosheep': { name: 'Sheep Wars', command: '/play prototype_sheepwars_two_six' },
  'quakesolo': { name: 'Quakecraft (Solo)', command: '/play quake_solo' },
  'quaketeams': { name: 'Quakecraft (Teams)', command: '/play quake_teams' },
  'ranked': { name: 'Ranked SkyWars', command: '/play ranked_normal' },
  'rush2': { name: 'Rush Doubles', command: '/play bedwars_eight_two_rush' },
  'rush4': { name: 'Rush 4v4v4v4', command: '/play bedwars_four_four_rush' },
  'scuba': { name: 'Scuba Simulator', command: '/play arcade_scuba_simulator' },
  'santa': { name: 'Santa Simulator', command: '/play arcade_santa_simulator' },
  'santasays': { name: 'Santa Says', command: '/play arcade_santa_says' },
  'sheepwars': { name: 'Sheep Wars', command: '/play wool_sheep_wars_two_six' },
  'skyblock': { name: 'SkyBlock', command: '/play sb' },
  'slime2': { name: 'Teams Slime', command: '/play teams_insane_slime' },
  'slimesolo': { name: 'Solo Slime', command: '/play solo_insane_slime' },
  'sumo': { name: 'Sumo Duels', command: '/play duels_sumo_duel' },
  'sw1': { name: 'SkyWars Duels (1v1)', command: '/play duels_sw_duel' },
  'sw2': { name: 'SkyWars Duels (2v2)', command: '/play duels_sw_doubles' },
  'tnt': { name: 'TNT Run', command: '/play tnt_tntrun' },
  'tntag': { name: 'TNT Tag', command: '/play tnt_tntag' },
  'tntwizards': { name: 'TNT Wizards', command: '/play tnt_capture' },
  'tkr': { name: 'Turbo Kart Racers', command: '/play tkr' },
  'towerwars2': { name: 'Tower Wars (Doubles)', command: '/play prototype_towerwars_team_of_two' },
  'towerwars1': { name: 'Tower Wars (Solo)', command: '/play prototype_towerwars_solo' },
  'uhc1': { name: 'UHC Duels (1v1)', command: '/play duels_uhc_duel' },
  'uhc2': { name: 'UHC Duels (2v2)', command: '/play duels_uhc_doubles' },
  'uhc4': { name: 'UHC Duels (4v4)', command: '/play duels_uhc_four' },
  'uhcmeetup': { name: 'UHC Deathmatch', command: '/play duels_uhc_meetup' },
  'uhcevents': { name: 'UHC Events Mode', command: '/play uhc_events' },
  'vampirez': { name: 'VampireZ', command: '/play vampirez' },
  'voidless2': { name: 'Voidless Doubles', command: '/play bedwars_eight_two_voidless' },
  'voidless4': { name: 'Voidless 4v4v4v4', command: '/play bedwars_four_four_voidless' },
  'zombiesp': { name: 'Zombies (Prison)', command: '/play arcade_zombies_prison' },
  'zombiesd': { name: 'Zombies (Dead End)', command: '/play arcade_zombies_dead_end' },
  'zombiesb': { name: 'Zombies (Bad Blood)', command: '/play arcade_zombies_bad_blood' },
  'zombiesa': { name: 'Zombies (Alien Arcadium)', command: '/play arcade_zombies_alien_arcadium' },
  'throwout': { name: 'Throw Out', command: '/play arcade_throw_out' },
  'walls': { name: 'The Walls', command: '/play walls' },
  'hideprop': { name: 'Hide and Seek (Prop Hunt)', command: '/play arcade_hide_and_seek_prop_hunt' },
  'hideparty': { name: 'Hide and Seek (Party Pooper)', command: '/play arcade_hide_and_seek_party_pooper' },
  'halloween': { name: 'Halloween Simulator', command: '/play arcade_halloween_simulator' }
};

module.exports = {
    mcColors,
    findClosestMinecraftColor,
    commandAliases,
    gameModeMap,
    quickQueueMap
};